'use client';

import { useState, useEffect } from 'react';
import { useAmbianceContext } from '@/providers/ambiance-provider';
import { AmbianceCompact } from './ambiance/ambiance-compact';
import { AmbianceExpanded } from './ambiance/ambiance-expanded';

interface AmbianceTrack {
  id: string;
  name: string;
  file: string;
  description?: string;
  artist?: string;
  provenance?: string;
}

// Track list - used by provider
export const AMBIANCE_TRACKS: AmbianceTrack[] = [
  {
    id: 'onae',
    name: 'Onae',
    file: '/music/OnaE.mp3',
    description: 'African Christmas calypso with sax and drums',
    artist: 'Papa',
    provenance: 'Generated by Suno AI'
  },
  {
    id: 'born-together',
    name: 'Born Together',
    file: '/music/Born_Together.mp3',
    description: 'Uplifting festive harmony with strings',
    artist: 'Various Artists',
    provenance: 'Generated by Suno AI'
  },
  {
    id: 'winter-bells',
    name: 'Winter Bells',
    file: '/music/Winter_Bells.mp3',
    description: 'Traditional winter bells ambiance',
    artist: 'Traditional',
    provenance: 'Generated by Suno AI'
  },
  {
    id: 'carol-chorus',
    name: 'Carol Chorus',
    file: '/music/Carol_Chorus.mp3',
    description: 'Joyful caroling voices in harmony',
    artist: 'Community Chorus',
    provenance: 'Generated by Suno AI'
  },
  {
    id: 'silent-night-ambiance',
    name: 'Silent Night Ambiance',
    file: '/music/Silent_Night_Ambiance.mp3',
    description: 'Peaceful, meditative arrangement',
    artist: 'Solo Piano',
    provenance: 'Generated by Suno AI'
  },
];

export function ChristmasAmbiance() {
  const [isMobile, setIsMobile] = useState(false);
  const [isHydrated, setIsHydrated] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false);

  const {
    isPlaying,
    isReady,
    isMuted,
    volume,
    currentTrackId,
    togglePlay,
    setMuted,
    setVolume,
    setTrackId,
  } = useAmbianceContext();

  // Detect mobile
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  // Hydration check
  useEffect(() => {
    setIsHydrated(true);
  }, []);

  if (!isHydrated) {
    return null;
  }

  const currentTrack = AMBIANCE_TRACKS.find(t => t.id === currentTrackId) || AMBIANCE_TRACKS[0];

  return (
    <div className="fixed bottom-6 left-6 z-40 select-none">
      {isExpanded ? (
        // Expanded view - in a modal/card
        <div className="bg-white rounded-2xl shadow-lg border border-primary/10 p-6 w-80 max-w-[calc(100vw-3rem)]">
          <AmbianceExpanded
            isPlaying={isPlaying}
            isReady={isReady}
            isMuted={isMuted}
            volume={volume}
            trackName={currentTrack.name}
            trackDescription={currentTrack.description}
            artist={currentTrack.artist}
            provenance={currentTrack.provenance}
            availableTracks={AMBIANCE_TRACKS}
            currentTrackId={currentTrackId}
            onTrackChange={setTrackId}
            onTogglePlay={togglePlay}
            onToggleMute={setMuted}
            onVolumeChange={setVolume}
            onToggleExpand={() => setIsExpanded(false)}
          />
        </div>
      ) : (
        // Compact view - inline with track info
        <div className="bg-white rounded-2xl shadow-lg border border-primary/10 px-4 py-3">
          <div className="space-y-2">
            {/* Track info line */}
            <div className="text-xs text-slate-600 truncate">
              <span className="font-semibold text-slate-700">{currentTrack.name}</span>
              {currentTrack.artist && (
                <span className="text-slate-500"> • {currentTrack.artist}</span>
              )}
            </div>
            {/* Controls */}
            <AmbianceCompact
              isPlaying={isPlaying}
              isReady={isReady}
              isMuted={isMuted}
              volume={volume}
              onTogglePlay={togglePlay}
              onToggleMute={setMuted}
              onVolumeChange={setVolume}
              onToggleExpand={() => setIsExpanded(true)}
              showVolumeSlider={!isMobile}
            />
          </div>
        </div>
      )}
    </div>
  );
}
