'use client';

import { useState, useEffect } from 'react';
// TODO: Ambiance hooks not yet fully implemented
// import { useAmbianceAudio } from '@/hooks/useAmbianceAudio';
// import { useAmbiancePreferences } from '@/hooks/useAmbiancePreferences';
// import { useAmbianceContext } from '@/providers/ambiance-provider';
import { AmbianceCompact } from './ambiance/ambiance-compact';
import { AmbianceExpanded } from './ambiance/ambiance-expanded';

interface AmbianceTrack {
  id: string;
  name: string;
  file: string;
  description?: string;
  artist?: string;
  provenance?: string;
}

const AMBIANCE_TRACKS: AmbianceTrack[] = [
  {
    id: 'onae',
    name: 'Onae',
    file: '/music/OnaE.mp3',
    description: 'African Christmas calypso with sax and drums',
    artist: 'Papa',
    provenance: 'Generated by Suno AI'
  },
  {
    id: 'born-together',
    name: 'Born Together',
    file: '/music/BORN TOGETHER (AN UBUNTU CHRISTMAS CAROL.mp3',
    description: 'Upbeat African Christmas with piano',
    artist: 'Papa',
    provenance: 'Generated by Suno AI'
  },
];

export function ChristmasAmbiance() {
  // TODO: AmbianceProvider implementation pending
  return null;
  /*
  const [isMobile, setIsMobile] = useState(false);
  const [isHydrated, setIsHydrated] = useState(false);
  const context = useAmbianceContext();

  // Detect mobile
  useEffect(() => {
    const checkMobile = () => {
      setIsMobile(window.innerWidth < 768);
    };
    checkMobile();
    window.addEventListener('resize', checkMobile);
    return () => window.removeEventListener('resize', checkMobile);
  }, []);

  // Get preferences
  const {
    preferences,
    isLoaded,
    setVolume,
    setMuted,
    setExpanded,
    setTrackId,
  } = useAmbiancePreferences(isMobile);

  // Get current track
  const currentTrack = AMBIANCE_TRACKS.find(t => t.id === preferences.trackId) || AMBIANCE_TRACKS[0];

  // Get audio controls
  const { isPlaying, isReady, togglePlay } = useAmbianceAudio({
    src: currentTrack.file,
    volume: preferences.volume,
    muted: preferences.muted,
  });

  // Hydration check
  useEffect(() => {
    setIsHydrated(true);
  }, []);

  if (!isHydrated || !isLoaded) {
    return null;
  }

  const showExpanded = preferences.expanded && !isMobile;

  return (
    <div className={`fixed z-[100] transition-all duration-300 ${
      isMobile ? 'bottom-4 right-4' : 'bottom-6 right-6'
    }`}>
      <div className={`bg-white/95 backdrop-blur-md rounded-full shadow-lg border border-primary/20 transition-all duration-300 ${
        showExpanded 
          ? 'rounded-3xl p-4 w-80' 
          : 'p-3 flex items-center gap-2'
      }`}>
        {showExpanded ? (
          <AmbianceExpanded
            isPlaying={isPlaying}
            isReady={isReady}
            isMuted={preferences.muted}
            volume={preferences.volume}
            trackName={currentTrack.name}
            trackDescription={currentTrack.description}
            artist={currentTrack.artist}
            provenance={currentTrack.provenance}
            availableTracks={AMBIANCE_TRACKS.map(t => ({ id: t.id, name: t.name }))}
            currentTrackId={preferences.trackId}
            onTrackChange={(trackId) => {
              setTrackId(trackId);
              const newTrack = AMBIANCE_TRACKS.find(t => t.id === trackId);
              if (newTrack) {
                // This will trigger loadTrack in the audio hook
                context.loadTrack(newTrack.file);
              }
            }}
            onTogglePlay={togglePlay}
            onToggleMute={() => setMuted(!preferences.muted)}
            onVolumeChange={setVolume}
            onToggleExpand={() => setExpanded(false)}
          />
        ) : (
          <AmbianceCompact
            isPlaying={isPlaying}
            isReady={isReady}
            isMuted={preferences.muted}
            volume={preferences.volume}
            onTogglePlay={togglePlay}
            onToggleMute={() => setMuted(!preferences.muted)}
            onVolumeChange={setVolume}
            onToggleExpand={() => setExpanded(true)}
            showVolumeSlider={!isMobile}
          />
        )}
      </div>
    </div>
  );
  */
}
