'use client';

import { Badge } from '@/components/ui/badge';
import { Sparkles } from 'lucide-react';

interface TranslationBadgeProps {
  source: 'ai_generated' | 'user_submitted';
  upvotes?: number;
  downvotes?: number;
  isCanonical?: boolean;
}

export function TranslationBadge({
  source,
  upvotes = 0,
  downvotes = 0,
  isCanonical = false,
}: TranslationBadgeProps) {
  const isAI = source === 'ai_generated';
  const totalVotes = upvotes + downvotes;
  const approvalRate = totalVotes > 0 ? Math.round((upvotes / totalVotes) * 100) : 0;

  return (
    <div className="flex items-center gap-1.5">
      {isAI ? (
        <Badge variant="outline" className="gap-1 bg-blue-50 border-blue-200 text-blue-700 text-xs" title="Generated by Gemini 3. Community refinement welcome!">
          <Sparkles className="w-3 h-3" />
          AI-Generated
        </Badge>
      ) : (
        <Badge variant="outline" className="gap-1 bg-green-50 border-green-200 text-green-700 text-xs" title={`Community translation (${approvalRate}% approved, ${totalVotes} votes)`}>
          <span className="font-bold">{approvalRate}%</span>
          Community
        </Badge>
      )}

      {isCanonical && (
        <Badge variant="secondary" className="text-xs">
          Official
        </Badge>
      )}
    </div>
  );
}
