import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@clerk/nextjs/server';
import { z } from 'zod';
import { getCarol } from '@/lib/carols';
import { 
  getCanonicalTranslation, 
  getOrCreateTranslation,
  getTranslationsForCarol,
} from '@/lib/translations';
import { translateCarolWithGemini } from '@/lib/ai';

const translationRequestSchema = z.object({
  carolId: z.string().min(1),
  language: z.string().min(1).max(10),
  languageName: z.string().min(1), // e.g., "Spanish", "French"
});

export async function POST(request: NextRequest) {
  try {
    const { userId } = await auth();

    // Optional auth - allow guest requests (they just won't earn rep)
    // Later: require auth for proposal voting

    const body = await request.json();
    const { carolId, language, languageName } = translationRequestSchema.parse(body);

    // Get original carol
    const carol = await getCarol(carolId);
    if (!carol) {
      return NextResponse.json(
        { error: 'Carol not found' },
        { status: 404 }
      );
    }

    // Check if translation already exists
    const existingTranslation = await getCanonicalTranslation(carolId, language);
    if (existingTranslation) {
      return NextResponse.json({
        success: true,
        translation: existingTranslation,
        source: existingTranslation.source,
        alternatives: await getTranslationsForCarol(carolId, language),
      });
    }

    // Translate using Gemini 3
    const translationData = await translateCarolWithGemini(
      carol.title,
      carol.lyrics || [],
      language,
      languageName
    );

    // Store translated version
    const translation = await getOrCreateTranslation(
      carolId,
      language,
      {
        title: translationData.title,
        lyrics: translationData.lyrics,
        source: 'ai_generated',
        isCanonical: 1,
        createdBy: userId || undefined,
      }
    );

    return NextResponse.json({
      success: true,
      translation,
      source: 'ai_generated',
      message: 'Translation generated by Gemini 3. Community refinement welcome!',
    });
  } catch (error) {
    if (error instanceof z.ZodError) {
      return NextResponse.json(
        { error: 'Invalid input', details: error.errors },
        { status: 400 }
      );
    }

    console.error('Error processing translation request:', error);
    return NextResponse.json(
      { error: 'Failed to translate carol' },
      { status: 500 }
    );
  }
}

/**
 * GET /api/carols/translate?carolId=xxx&language=es
 * Retrieve existing translation without generating new one
 */
export async function GET(request: NextRequest) {
  try {
    const searchParams = request.nextUrl.searchParams;
    const carolId = searchParams.get('carolId');
    const language = searchParams.get('language') || 'en';

    if (!carolId) {
      return NextResponse.json(
        { error: 'Missing carolId parameter' },
        { status: 400 }
      );
    }

    // Get canonical translation
    const translation = await getCanonicalTranslation(carolId, language);
    if (!translation) {
      return NextResponse.json(
        { error: 'Translation not found. Use POST to generate.' },
        { status: 404 }
      );
    }

    // Get all alternatives
    const alternatives = await getTranslationsForCarol(carolId, language);

    return NextResponse.json({
      success: true,
      translation,
      alternatives: alternatives.filter(t => t.id !== translation.id),
    });
  } catch (error) {
    console.error('Error fetching translation:', error);
    return NextResponse.json(
      { error: 'Failed to fetch translation' },
      { status: 500 }
    );
  }
}
